name: CI/CD
on: push
jobs:
  build:
    env:
      is_master_branch: ${{github.ref == 'refs/heads/master'}}
      is_release_branch: ${{startsWith(github.ref, 'refs/heads/release') == true}}
      is_tag: ${{startsWith(github.ref, 'refs/tags') == true}}
    runs-on: windows-latest
    steps:
      - name: Setup whether job needs to handle NuGet-packaging
        id: needs_packaging
        env:
          needs_packaging: ${{env.is_master_branch == 'true' || env.is_release_branch == 'true' || env.is_tag == 'true'}}
        run: echo "::set-output name=value::$env:needs_packaging"

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Fetch history for versioning
        if: steps.needs_packaging.outputs.value == 'true'
        run: git fetch --prune --unshallow

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Build project
        run: dotnet build -c Release -f netstandard2.1 -o bin/ src/HybridModelBinding

      - name: Create NuGet-package
        if: steps.needs_packaging.outputs.value == 'true'
        run: dotnet pack --no-build -p:OutputPath=../../bin/ src/HybridModelBinding

      - name: Publish NuGet-package
        if: steps.needs_packaging.outputs.value == 'true'
        run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_TOKEN}} -n true bin\*.nupkg
